book_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.test_apps, name='main_page'),
    path('directors', views.all_directors),
    path('directors/<int:number_of_director>', views.one_director, name='one_dir'),
    path('feedback', views.feedback),
    path('done', views.done),
    path('actor/<int:character_id>', views.info, name='character'),
    path('<slug:slug_book>', views.one, name='one_book'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.index_title = 'Главная страница админки'
admin.site.site_header = 'Админка Букиниста'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_app.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

book_app/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here
class FeedBack(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    feedback = models.TextField(max_length=150)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])


class Author(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f'{self.name} {self.surname}'

    def get_author(self):
        return reverse('one_dir', args=[self.id])


class Character(models.Model):
    MALE = 'М'
    FEMALE = 'Ж'
    GENDER_CHOICES = [
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина'),
    ]
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    gender = models.CharField(max_length=3, choices=GENDER_CHOICES, default=MALE)

    def __str__(self):
        if self.gender == self.MALE:
            return f'Актёр {self.name} {self.surname}'
        return f'Актриса {self.name} {self.surname}'

    def get_actor(self):
        return reverse('character', args=[self.id])


class Book(models.Model):
    RUB = 'RUB'
    USD = 'USD'
    EUR = 'EUR'

    CURRENCY_CHOICES = [
        (RUB, 'Rubles'),
        (USD, 'Dollars'),
        (EUR, 'Euro'),
    ]

    title = models.CharField(max_length=70)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    year = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1950), MaxValueValidator(2023)])
    budget = models.IntegerField(blank=True, default=50000, validators=[MinValueValidator(10000)])
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=USD)
    is_best_selling = models.BooleanField(default=True)
    director = models.ForeignKey(Author, on_delete=models.PROTECT, null=True)
    slug = models.SlugField(default='', null=False)
    actors = models.ManyToManyField(Character)

    def __str__(self):
        return f'{self.title} -> рейтинг: {self.rating} -> год: {self.year}'

    def get_book(self):
        return reverse('one_book', args=[self.slug])

book_app/forms.py
from django import forms


class FeedBackForm(forms.Form):
    name = forms.CharField(min_length=3, max_length=12)
    surname = forms.CharField(min_length=3, max_length=12)
    feedback = forms.CharField(widget=forms.Textarea(attrs={'cols': 20, 'rows': 5}))
    rating = forms.IntegerField(min_value=1, max_value=5)

book_app/views.py
from django.http import HttpResponseRedirect
from django.db.models import Max, Min, Count
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, Character, FeedBack
from .forms import FeedBackForm


# Create your views here.

def test_apps(request):
    books = Book.objects.order_by('title')
    agg = books.aggregate(Max('rating'), Min('rating'), Count('title'))
    return render(request, 'book_app/index.html', {
        'books': books,
        'agg': agg
    })


def one(request, slug_book: str):
    book = get_object_or_404(Book, slug=slug_book)
    return render(request, 'book_app/one_book.html', {
        'number': slug_book,
        'book': book
    })


def all_directors(request):
    directors = Author.objects.all()
    characters = Character.objects.all()
    return render(request, 'book_app/all_dir.html', context={
        'directors': directors,
        'characters': characters,
    })


def one_director(request, number_of_director: id):
    number = get_object_or_404(Author, id=number_of_director)
    return render(request, 'book_app/one_dir.html', context={
        'number': number_of_director,
        'author': number,
    })


def info(request, character_id: id):
    character = get_object_or_404(Character, id=character_id)
    return render(request, 'book_app/info.html', context={
        'character': character,
        'character_id': character_id
    })


def feedback(request):
    if request.method == 'POST':
        form = FeedBackForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            feed = FeedBack(
                name=form.cleaned_data['name'],
                surname=form.cleaned_data['surname'],
                feedback=form.cleaned_data['feedback'],
                rating=form.cleaned_data['rating'],
            )
            feed.save()
            return HttpResponseRedirect('/done')
    else:
        form = FeedBackForm()
    return render(request, 'book_app/contacts.html', context={
        'form': form
    })


def done(request):
    return render(request, 'book_app/done_form.html')

book_app/templates/book_app/all_dir.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Авторы {% endblock %}
{% block css_addition %}
<link rel="stylesheet" href="{% static 'book_app/css/style.css'%}">
{% endblock %}

{% block content %}
<h3>Список Авторов</h3>
<ul>
    {% for director in directors %}
        <li class="main_list"><a href="{{director.get_author}}">{{director}}</a></li>
    {% endfor %}
</ul>
<hr>
<br>
<h3>Список Авторов</h3>
<ul>
    {% for char in characters %}
        <li class="main_list"><a href="{{char.get_actor}}">{{char}}</a></li>
    {% endfor %}
</ul>
<hr>
{% endblock %}

book_app/templates/book_app/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Форма {% endblock %}
{% block css_addition %}
<link rel="stylesheet" href="{% static 'book_app/css/style.css'%}">
{% endblock %}

{% block content %}
<main>
    <form action="" method="post">
        <h2> Контактная информация </h2>
        {% csrf_token %}
        {% for field in form %}
        <div class="form_fields">
            {{field.label_tag}}
            {{field.errors}}
            {{field}}
        </div>
        {% endfor %}
        <button type="submit" class="form_btn">Отправить</button>
    </form>
</main>
{% endblock %}

book_app/templates/book_app/done_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Форма {% endblock %}
{% block css_addition %}
<link rel="stylesheet" href="{% static 'book_app/css/style.css'%}">
{% endblock %}

{% block content %}
<main>
    <h2> Контактная информация </h2>
</main>
{% endblock %}

book_app/templates/book_app/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Все фильмы {% endblock %}


{% block content %}
<main class="main">
    <h2>Список всех фильмов</h2>
    <ul>
        {% for book in books %}
            <li class="main_list"><a href="{{ book.get_book }}">{{ book.title }}</a>, рейтинг = {{ book.rating }},
                бестселлер - {{ book.is_best_selling }}</li>
        {% endfor %}
    </ul>
    <h4 class="add_info"> Максимальный рейтинг фильма - {{agg.rating__max}}</h4>
    <h4 class="add_info"> Минимальный рейтинг фильма - {{agg.rating__min}}</h4>
    <h4 class="add_info"> Количество фильмов на сайте = {{agg.title__count}}</h4>
    </main>
{% endblock %}

book_app/templates/book_app/info.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Автор {% endblock %}
{% block css_addition %}
<link rel="stylesheet" href="{% static 'book_app/css/style.css'%}">
{% endblock %}

{% block content %}
<main>
    <h2> Актёр </h2>
    <h4>Имя - {{character.name}}</h4>
    <h4>Фамилия - {{character.surname}}</h4>
    <h4>Пол - {{character.gender}}</h4>
</main>
{% endblock %}

book_app/templates/book_app/one_book.html
{% extends 'base.html' %}

{% block title %} Одна книга {% endblock %}

{% block content %}
    <h2>Одна книга</h2>
    <p>Название книги {{book.title}}</p>
    <p>Рейтинг {{book.rating}}</p>
    <p>Бюджет {{book.budget}}</p>
    <p>Год {{book.year}}</p>
<hr>
    <h2>Информация о режисёре</h2>
    <p>Имя {{book.director.name}}</p>
    <p>Фамилия {{book.director.surname}}</p>
    <p>Почта {{book.director.email}}</p>
<hr>
    <h2>Персонажи книги</h2>
    <ol>
        {% for char in book.actors.all %}
        <li> {{char}} </li>
        <hr>
        {% endfor %}
    </ol>
{% endblock %}

book_app/templates/book_app/one_dir.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Автор {% endblock %}
{% block css_addition %}
<link rel="stylesheet" href="{% static 'book_app/css/style.css'%}">
{% endblock %}

{% block content %}
<main>
    <h2> Автор </h2>
    <h4>Имя - {{author.name}}</h4>
    <h4>Фамилия - {{author.surname}}</h4>
    <h4>Email - {{author.email}}</h4>
    <hr>
    <h2> Книги написанные автором </h2>
    <ol>
        {% for i in author.book_set.all %}
            <li>{{i}}</li>
        {% endfor %}
    </ol>
</main>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css'%}">
  {% block css_addition %} {% endblock %}
</head>
<body>
<header>
  <div>
    <h1>My Website</h1>
  </div>
  <nav>
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/directors">About</a></li>
      <li><a href="/feedback">Contact</a></li>
    </ul>
  </nav>
</header>
{% block content %} {% endblock %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p>Copyright © 2020 Your Company</p>
      </div>
      <div class="col-md-6">
        <ul class="list-inline">
          <li class="list-inline-item"><a class="link" href="#">Privacy</a></li>
          <li class="list-inline-item"><a class="link" href="#">Terms</a></li>
          <li class="list-inline-item"><a class="link" href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
</body>
</html>